version: 0.2

env:
  variables:
    # Tell your FastAPI code where to find the test database
    DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/python_fastapi_db"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip setuptools wheel
      - pip install uv
      - if [ -f "requirements.txt" ]; then uv pip install --system -r requirements.txt; fi
      - uv pip install --system bandit pytest pytest-cov

  pre_build:
    commands:
      - echo "Starting background PostgreSQL database for unit tests..."
      - docker run --name test-postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=python_fastapi_db -p 5432:5432 -d postgres:15-alpine
      - echo "Waiting for database to accept connections..."
      - sleep 5 # Gives the container a few seconds to spin up completely
      - echo "Running security scans..."
      - python -m bandit -r . -x tests/

  build:
    commands:
      - echo "Executing unit tests..."
      - python -m pytest tests/

  post_build:
    commands:
      - echo "Build finished on $(date)"

artifacts:
  files:
    - '**/*'
